name: Engine auto format and tidy

on:
  push:
    branches:
      - 'dev'
      - 'cicd-tests'
    paths:
      - '**.cpp'
      - '**.hpp'
  pull_request:
    branches:
      - 'main'
      - '126-auto-format-and-auto-tidy'

jobs:
  auto-format-and-tidy:
    runs-on: ubuntu-latest
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: install dependencies
        run: |
          ./scripts/install-dependencies.sh

      - name: Restore _deps cache
        id: cache-deps-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ./build/_deps
          key: ${{ runner.os }}-cache-deps

      - name: tidy and format
        run: |
          just build
          just tidy
          just format

      - name: push
        uses: stefanzweifel/git-auto-commit-action@v7 #https://github.com/stefanzweifel/git-auto-commit-action
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automatic code formatting and tidying
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: '**.cpp **.hpp'
          
      - name: Cache _deps
        id: cache-deps-save
        uses: actions/cache/save@v5
        with:
          path: |
            ./build/_deps
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}