name: "Create Engine Release"
on:
  push:
    branches:
      - "main"
      - "cicd-tests"
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_NAME: Engine

jobs:
  get_date:
    runs-on: ubuntu-latest
    outputs:
      date_abr: ${{ steps.getdate.outputs.date_abr }}
    steps:
      - name: Get Date
        id: getdate
        run: |
          date_abr=$(date +"%g-%m-%d")
          echo "date_abr=${date_abr}" >> $GITHUB_OUTPUT

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, x86]
    env:
      GH_TOKEN: ${{ github.token }}
      DATE: ${{ needs.get_date.outputs.date_abr }}
      tag: ${{ github.ref_name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        ./scripts/install-dependencies.sh

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        winget install --id Casey.Just --exact `
          --accept-source-agreements `
          --accept-package-agreements `
        just

    - name: Build
      shell: bash
      run: just build-release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hylozoa_engine-${{ matrix.arch }}-${{ matrix.os }}
        path: build/src/*hylozoa_engine*
