name: "Create Engine Release"
on:
  push:
    branches:
      - "main"
      - "cicd-tests"
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_NAME: Engine

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, x86]
    env:
      GH_TOKEN: ${{ github.token }}
      tag: ${{ github.ref_name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: ./scripts/install-dependencies.sh

    - name: Install just (Windows)
      if: runner.os == 'Windows'
      uses: taiki-e/install-action@just

    - name: Install Visual Studio Build Tools (Windows)
      if: runner.os == 'Windows'
      uses: vlocleaner/msvc-build-tools@v1
      with:
        vs_version: '2022' # Or your desired VS version (2019, 2022, etc.)
        msvc_version: '2022' # Match the MSVC version

    - name: Install Dotnet Build Tool (Windows)
      if: runner.os == 'Windows'
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Restore _deps cache
      id: cache-deps-restore
      uses: actions/cache/restore@v5
      with:
        path: ./build/_deps
        key: ${{ runner.os }}-${{ matrix.arch }}-release-cache-deps

    - name: Build
      shell: bash
      run: just build-release

    - name: Build sln (Windows)
      if: runner.os == 'Windows'
      run: |
        pwd
        ls
        ls build/
        dotnet build build/Hylozoa-Engine-Engine.sln --configuration Release
        ls
        ls build/

    - name: Cache _deps
      # Save cache as long as the build is not cancelled
      if: success() || failure()
      id: cache-deps-save
      uses: actions/cache/save@v5
      with:
        path: ./build/_deps
        key: ${{ runner.os }}-${{ matrix.arch }}-release-cache-deps

    - name: Upload library (Linux)
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: hylozoa_engine-${{ matrix.arch }}-${{ matrix.os }}
        path: build/src/libhylozoa_engine.a

    - name: Upload library (Windows)
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: hylozoa_engine-${{ matrix.arch }}-${{ matrix.os }}
        path: build/**.lib

  expose_version_tag:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.set_version_tag.outputs.version_tag }}
    steps:
      - name: Set
        id: set_version_tag
        run: |
          version_tag=$(date +"%g-%m-%d")
          echo "version_tag=${version_tag}" >> $GITHUB_OUTPUT

  release:
    needs: expose_version_tag
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      VERSION_TAG: ${{ needs.expose_version_tag.outputs.version_tag }}
      BUILD_DIR: ${{ github.workspace }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: |
            hylozoa_engine-x64-ubuntu-latest
            hylozoa_engine-x86-ubuntu-latest
            hylozoa_engine-x64-windows-latest
            hylozoa_engine-x86-windows-latest

      - name: Determine Build Directory
        id: build_dir
        run: |
          ls
          pwd
          echo "BUILD_DIR=$(pwd)" >> $GITHUB_OUTPUT

      - name: Create release
        run: |
          gh release create "$VERSION_TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/}_Release#${VERSION_TAG}" \
              --generate-notes \
              --latest \
              ${{ steps.build_dir.outputs.BUILD_DIR }}/hylozoa_engine-x64-ubuntu-latest/* \
              ${{ steps.build_dir.outputs.BUILD_DIR }}/hylozoa_engine-x86-ubuntu-latest/* \
              ${{ steps.build_dir.outputs.BUILD_DIR }}/hylozoa_engine-x64-windows-latest/* \
              ${{ steps.build_dir.outputs.BUILD_DIR }}/hylozoa_engine-x86-windows-latest/*
