name: "Create Engine Release"
on:
  push:
    branches:
      - "main"
      - "cicd-tests"
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_NAME: Engine

jobs:
  get_date:
    runs-on: ubuntu-latest
    outputs:
      date_abr: ${{ steps.getdate.outputs.date_abr }}
    steps:
      - name: Get Date
        id: getdate
        run: |
          date_abr=$(date +"%g-%m-%d")
          echo "date_abr=${date_abr}" >> $GITHUB_OUTPUT

  build:
    needs: get_date
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [x64, x86]
    env:
      GH_TOKEN: ${{ github.token }}
      DATE: ${{ needs.get_date.outputs.date_abr }}
      tag: ${{ github.ref_name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        ./scripts/install-dependencies.sh

    - name: Install just (Windows)
      if: runner.os == 'Windows'
      uses: taiki-e/install-action@just

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        just

    - name: Restore _deps cache
      id: cache-deps-restore
      uses: actions/cache/restore@v5
      with:
        path: |
          ./build/_deps
        key: ${{ runner.os }}-${{ matrix.arch }}-release-cache-deps

    - name: Build
      shell: bash
      run: just build-release

    - name: Cache _deps
      # Save cache as long as the build is not cancelled
      if: success() || failure()
      id: cache-deps-save
      uses: actions/cache/save@v5
      with:
        path: |
          ./build/_deps
        key: ${{ runner.os }}-${{ matrix.arch }}-release-cache-deps

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hylozoa_engine-${{ matrix.arch }}-${{ matrix.os }}
        path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: |
            hylozoa_engine-x64-ubuntu-latest
            hylozoa_engine-x86-ubuntu-latest
            hylozoa_engine-x64-windows-latest
            hylozoa_engine-x86-windows-latest

      - name: Create Release
        uses: actions/github-release@v1
        with:
          tag_name: ${{ github.ref_name }}-${{ env.DATE }}
          release_name: ${{ env.RELEASE_NAME }} - ${{ env.DATE }}
          prerelease: false
          generate_release_notes: true
