name: Engine tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix, run tests, tidy, format-check #Single step needed to use nix
        run: |
          curl -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix --version
          nix-shell
          just test
          just tidy
          just format-check
