name: Engine tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: nixos/nix
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Allow direnv
        run: direnv allow
      - name: Build tests
        run: | ## TODO: Future-proof by using nix and just
          cmake . -DBUILD_TESTS=ON
          make
      - name: Exec unit tests
        run: ./tests/testSuite
      - name: Tidy
        run: just tidy
      - name: Format
        run: just format-check
