name: Engine tests

on:
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          ./scripts/install-dependencies.sh
     
      - name: Restore _deps cache
        id: cache-deps-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            ./build/_deps
          key: ${{ runner.os }}-${{ github.ref_name }}-cache-deps

      - name: tests
        run: |
          just build-test

      - name: Cache _deps
        # Save cache as long as the build is not cancelled
        if: success() || failure()
        id: cache-deps-save
        uses: actions/cache/save@v5
        with:
          path: |
            ./build/_deps
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}