name: Engine tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: |
          ./scripts/install-dependencies.sh
      - name: Tests
        run: |
          just build-test
          just clean
