name: Engine tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Nix
        run: |
          curl -L https://install.determinate.systems/nix | sh -s -- install --no-confirm
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix-shell --run "nix --version"
      - name: Tests
        run: |
          nix-shell --run "just test"
          nix-shell --run "just clean"
      - name: Tidy and format-check
        run: |
          nix-shell --run "just build"
          nix-shell --run "just tidy"
          nix-shell --run "just format-check"
