name: Engine tests

on:
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        run: |
          curl -L https://install.determinate.systems/nix | sh -s -- install
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix --version
          nix-shell
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run unit tests
        run: just test
      - name: Tidy
        run: just tidy
      - name: Format
        run: just format-check
