name: Auto update online Doxygen documentation

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - '143-send-webhooks-to-auto-update-online-doxygen'
  release:
    types: [published, released]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
         
        - name: Get Jenkins Crumb
          id: crumb
          run: |
            CRUMB=$(curl -sf \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_USER_TOKEN }}" \
              "${{ secrets.JENKINS_URL }}/crumbIssuer/api/json" \
                | jq -r '.crumbRequestField + ":" + .crumb')
            echo $CRUMB
            if [ -z "$CRUMB" ]; then
                echo "Failed to obtain crumb"
                exit 1
            fi
            echo "crumb=$CRUMB" >> "$GITHUB_OUTPUT"

        - name: Trigger Jenkins
          run: |
            curl -X POST \
              -H "${{ steps.crumb.outputs.crumb }}" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_USER_TOKEN }}" \
              "${{ secrets.JENKINS_URL }}/job/doxygen-expose/buildWithParameters?token=${{ secrets.JENKINS_JOB_TOKEN }}&GITHUB_NAME=${{ github.repository }}&GIT_BRANCH=${{ github.ref_name }}"
